# These are supported funding model platforms

github: guilhermelinosp
patreon: 
open_collective: guilhermelinosp
ko_fi: guilhermelinosp
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: 
