version: '3.9'
services:
  open-mongo:
    container_name: open-mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sa
      - MONGO_INITDB_ROOT_PASSWORD=@TXVkYXJAMTIz2023

  open-mssql:
    container_name: open-mssql
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@TXVkYXJAMTIz2023
      - MSSQL_PID=Developer

  open-rabbitmq:
    container_name: open-rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mssql-data:
  mongo-data:
  rabbitmq-data:
